return {
	-- Movement
	UP_KEY = Enum.KeyCode.W,
	LEFT_KEY = Enum.KeyCode.A,
	DOWN_KEY = Enum.KeyCode.S,
	RIGHT_KEY = Enum.KeyCode.D,
	JUMP_KEY = Enum.KeyCode.Space,
	DOUBLE_JUMP_KEY = Enum.KeyCode.Space,
	SLIDE_KEY = Enum.KeyCode.LeftControl,
	DASH_KEY = Enum.KeyCode.LeftShift,

	-- Combat
	JAB_KEY = Enum.KeyCode.MouseLeftButton,
	HEAVY_KEY = Enum.KeyCode.MouseRightButton,
	SHIELD_KEY = Enum.KeyCode.E,
}
